import { useRouter } from 'next/router'
import { FormataBRL } from 'utils/ConvertCurrency'
import Image from 'next/image'
import FormularioProduto from 'components/FormularioProduto/Formulario'
import dbConnect from 'services/connect'
import Product from 'models/product'
import { DataBase } from 'interface/ServerSideDataBase'
import Head from 'next/head'

//TODO Revisar

export async function getServerSideProps() {
  dbConnect.connect()
  const database = await Product.find();
  dbConnect.disconnect()
  return {
    props: { db: JSON.parse(JSON.stringify(database)) }
  }
}

const Post = ({ db }: DataBase) => {
  console.log(db)
  const router = useRouter()
  const { id } = router.query
  const array = db.filter(item => item._id === id)

  return (
    <>
      <Head>
        <title>MagiCandy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className='bg-backgroundPink flex justify-center items-center p-12 py-16'>
        {array.map(item => (
          <div className='bg-white text-black rounded-lg drop-shadow-xl border-2 border-fontPurple p-2 max-w-[1000px]' key={item._id}>
            <div className='flex flex-col md:flex-row justify-between'>
              <Image src={item.Src} alt={item.Alt} width={500} height={400} className='rounded-lg w-full grow md:w-[50%]'></Image>
              <div className='px-8 flex flex-col'>
                <h1 className='text-2xl my-6 text-fontPurple font-kalam ' >
                  {item.ProductTitle}
                </h1>
                <div className='self-center'>
                  <span className='text-xl text-start mb-[3rem] font-semibold '>
                    {`Preço: ${FormataBRL(item.ProductPrice)}`}
                  </span>
                  <FormularioProduto Price={item.ProductPrice} _id={item._id} Name={item.ProductTitle} Imagem={item.Src} />
                </div>
              </div>
            </div>
            <p className='mt-2 text-justify indent-4 text-xl p-4'>{item.Description}</p>
          </div>
        ))}
      </main>
    </>
  )
}

export default Post