import React from 'react'
import Button from '@ui/Button'
import Footer from '@ui/Footer'
import Navbar from '@ui/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import NotFound from 'public/page404.png'
import { AiOutlineArrowLeft } from 'react-icons/ai'

//TODO Revisar

export default function Custom404() {
  return (
    <>
      <Head>
        <title>MagiCandy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Navbar />
      <main className='bg-backgroundPink min-h-[calc(100vh-379px)] flex justify-center items-center'>
        <div className='px-48 flex items-center gap-32'>
          <div className='flex flex-col items-center'>
            <p className='font-kalam text-2xl'>Não achou o que estava procurando?</p>
            <div className='flex items-center'>
              <AiOutlineArrowLeft />
              <Button value='Voltar' type='LINK' href='../' />
            </div>
          </div>
          <div className='flex flex-col flex-wrap-reverse'>
            <Image src={NotFound} alt='foto de garotos olhando atráves de donuts' className='rounded-lg' width={600} height={400} />
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

