import React from 'react'
import Button from '@ui/Button'
import Head from 'next/head'
import Image from 'next/image'
import NotFound from 'public/page404.png'
import { AiOutlineArrowLeft } from 'react-icons/ai'
import Link from 'next/link'

//TODO Revisar

export default function Custom404() {
  return (
    <>
      <Head>
        <title>MagiCandy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className='bg-backgroundPink min-h-[calc(100vh-316px)] flex justify-center items-center'>
        <div className='bg-backgroundWhite flex items-center border-2 border-fontPurple rounded-lg'>
          <div className='flex flex-col items-center px-20'>
            <p className='font-kalam text-2xl'>Não achou o que estava procurando?</p>
            <div className='flex items-center'>
              <Link 
                className='flex items-center justify-center gap-2 cursor-pointer text-lg p-2  mx-auto radius-5 ring-2 my-[1rem] ring-backgroundPink font-kalam rounded-lg select-none'
                href='../produtos'
              >
                <AiOutlineArrowLeft />Ver produtos
              </Link>
            </div>
          </div>
          <div className='flex flex-col flex-wrap-reverse'>
            <Image src={NotFound} alt='foto de garotos olhando atráves de donuts' className='rounded-r-lg' width={600} height={400} />
          </div>
        </div>
      </main>
    </>
  )
}

