import Button from '@ui/Button'
import Fields from '@ui/Fields/Fields'
import Head from 'next/head'
import React from 'react'


function checkout() {
  return (
    <>
      <Head>
        <title>MagiCandy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className='bg-backgroundPink flex flex-col justify-center items-center p-12 py-16'>
        <div className='flex rounded-lg border-2 border-fontPurple overflow-hidden'>
          <form
            className='flex flex-col gap-4 w-full  bg-backgroundWhite p-10 rounded-r-lg'
          // onSubmit={onSubmitHandler}
          >
            <div className='pt-4 text-center'>
              <h1 className='text-2xl font-kalam text-fontPurple font-semibold'>Preencha as informações abaixo</h1>
            </div>
            <div className='flex gap-24'>
              <div>

                <Fields
                  Name="name"
                  Label="Nome *"
                  Type="text"
                />

                <Fields
                  Name="Email"
                  Label="E-mail "
                  Type="email"
                />

                <Fields
                  Name="cep"
                  Label="Cep *"
                  Type="text"
                />

              </div>
              <div>

                <Fields
                  Name="Sobrenome"
                  Label="Sobrenome "
                  Type="text"
                />

                <Fields
                  Name="cpf"
                  Label="CPF *"
                  Type="text"
                />

                <Fields
                  Name="telephone"
                  Label="Telefone *"
                  Type="tel"
                />

              </div>
            </div>
          </form>
        </div>
      </main>
    </>
  )
}

export default checkout