import Head from 'next/head'
import Card from '@ui/Card'
import dbConnect from 'services/connect'
import Product from 'models/product'
import { DataBase } from 'interface/ServerSideDataBase'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import unicornImg from 'public/unicorn2.png'
import CategoryCard from '@ui/CategoryCard'


export async function getStaticProps() {
	dbConnect.connect()
	const database = await Product.find();
	dbConnect.disconnect()
	const DataBaseSerialize = JSON.parse(JSON.stringify(database))
	const db = DataBaseSerialize.sort(() => 0.5 - Math.random()).splice(0, 3);
	return {
		props: { db }
	}
}

export default function Home({ db }: DataBase) {
	const [domLoaded, setDomLoaded] = useState(false)
	useEffect(() => {
		setDomLoaded(true);
	}, []);

	return (
		<>
			<Head>
				<title>MagiCandy</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<main className='flex flex-col items-center gap-8 min-h-screen w-full min-w-[320px]  bg-backgroundWhite overflow-x-hidden pb-10'>

				<section className="h-[calc(100vh_-_146px)] w-screen overflow-hidden relative flex items-center justify-center">
					<div className="opacity-90 w-full h-full">
						{domLoaded && (
							<video
								className="object-fill h-full w-full overflow-hidden"
								autoPlay
								loop
								muted
								preload="auto"
								playsInline>
								<source src="/magicandy.mp4" type='video/mp4' />
							</video>
						)}
					</div>
					<div className="flex flex-col justify-center items-center gap-6 max-w-[900px] text-backgroundWhite font-kalam absolute backdrop-blur-sm bg-black/30 border-none rounded-xl p-8">
						<div className='flex items-center justify-center gap-6'>
							<Image
								className='w-[80px]'
								src={unicornImg}
								width={45}
								height={45}
								alt=""
							/>
							<h2 className='text-6xl'>Magicandy</h2>
						</div>
						<p className='text-2xl text-justify teste'>Criada em 2023, a partir de um sonho e um compromisso, de fazer nossos produtos com amor e qualidade, para que em cada fatia, cada mordida e cada suspiro, possamos compartilhar com vocês a magia da felicidade. </p>
					</div>
				</section>

				<section className='max-w-[1200px]'>
					<div className=' items-center grid-cards min-w-[900px]'>
						<CategoryCard
							productTitle="Tortas"
							Src="/products/red-velvet-cake.png"
							Alt="Um bolo"
							>
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum ducimus quae minima recusandae libero iusto unde soluta repudiandae maiores quia, fuga asperiores quidem ullam, explicabo, eum esse quod impedit. Commodi.
						</CategoryCard>
						<CategoryCard
							productTitle="Brownies"
							Src="/products/brownie-morango.png"
							Alt="Um bolo"
							>
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum ducimus quae minima recusandae libero iusto unde soluta repudiandae maiores quia, fuga asperiores quidem ullam, explicabo, eum esse quod impedit. Commodi.
						</CategoryCard>
						<CategoryCard
							productTitle="Donuts"
							Src="/products/donuts-geleia.png"
							Alt=""
							>
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum ducimus quae minima recusandae libero iusto unde soluta repudiandae maiores quia, fuga asperiores quidem ullam, explicabo, eum esse quod impedit. Commodi.
						</CategoryCard>
					</div>
				</section>
			</main>
		</>
	)
}
