import Footer from '@ui/Footer'
import Navbar from '@ui/Navbar'
import Head from 'next/head'
import React from 'react'

function login() {
  return (
    <>
      <Navbar />
      <Head>
        <title>MagiCandy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>login</div>
      <Footer />
    </>
  )
}

export default login